services:
  client:
    build:
      dockerfile: apps/client/Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - server
  server:
    build:
      dockerfile: apps/server/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - apps/server/.env.docker
    volumes:
      - ./apps/server/.env.docker:/app/packages/database/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  postgres:
